18-349 Kernel: i2c.c File Reference
i2c.c File Reference
I2C driver.
#include <kstdint.h>
#include <BCM2836.h>
#include <gpio.h>
#include <printk.h>
Macros
#define I2C_CLK_100KHZ 0x5dc
I2C Clock speeds.
#define I2C1_SDA 2
I2C data pin.
#define I2C1_SCL 3
I2C clock pin.
#define I2C_ENB 0x8000
Enables I2C.
#define CLEAR_FLAGS 0x102
Clears Done and ERR ACK flags.
#define CLEAR_FIFO 0x30
Clear FIFO.
#define ENB_WRITE 0xFFFFFFFE
Enable write type.
#define ENB_READ 0x1
Enable read type.
#define ENB_TRANSFER 0x80
Enable transfer.
#define TXD 0x10
Check whether FIFO is full.
#define DONE_XFER 0x2
Check whether transfer is done.
#define I2C_CONTROL_REG (volatile uint32_t *)(MMIO_BASE_PHYSICAL +0x804000 + 0x0)
physical address of CONTROL_REG register
#define I2C_STATUS_REG (volatile uint32_t *)(MMIO_BASE_PHYSICAL +0x804000 + 0x4)
physical address of STATUS_REG register
#define I2C_DLEN_REG (volatile uint32_t *)(MMIO_BASE_PHYSICAL +0x804000 + 0x8)
physical address of DLEN_REG register
#define I2C_ADDRESS_REG (volatile uint32_t *)(MMIO_BASE_PHYSICAL +0x804000 + 0xc)
physical address of ADDRESS_REG register
#define I2C_FIFO_REG (volatile uint32_t *)(MMIO_BASE_PHYSICAL +0x804000 + 0x10)
physical address of FIFO register
#define I2C_CLKDIVIDER_REG (volatile uint32_t *)(MMIO_BASE_PHYSICAL +0x804000 + 0x14)
physical address of CLKDIVIDER_REG register
#define I2C_DELAY_REG (volatile uint32_t *)(MMIO_BASE_PHYSICAL +0x804000 + 0x18)
physical address of DELAY_REG register
#define I2C_CLKT_REG (volatile uint32_t *)(MMIO_BASE_PHYSICAL +0x804000 + 0x1C)
physical address of CLKT_REG register
Functions
void i2c_master_init (uint16_t clk)
initializes the I2C module
uint8_t i2c_master_write (uint8_t *buf, uint16_t len, uint8_t addr)
writes to I2C device
uint8_t i2c_master_read (uint8_t *buf, uint16_t len, uint8_t addr)
reads from I2C device
Variables
static volatile uint32_t * i2c_control_reg = (volatile uint32_t*) I2C_CONTROL_REG
physical address of CONTROL_REG register
static volatile uint32_t * i2c_status_reg = (volatile uint32_t*) I2C_STATUS_REG
physical address of STATUS_REG register
static volatile uint32_t * i2c_dlen_reg = (volatile uint32_t*) I2C_DLEN_REG
physical address of DLEN_REG register
static volatile uint32_t * i2c_address_reg = (volatile uint32_t*) I2C_ADDRESS_REG
physical address of ADDRESS_REG register
static volatile uint32_t * i2c_fifo_reg = (volatile uint32_t*) I2C_FIFO_REG
physical address of FIFO register
static volatile uint32_t * i2c_clkdivider_reg = (volatile uint32_t*) I2C_CLKDIVIDER_REG
physical address of CLKDIVIDER_REG register
Detailed Description
I2C driver.
Date
10/03/2016
Author
Philip Lee plee2.nosp@m.@and.nosp@m.rew.c.nosp@m.mu.e.nosp@m.du
Saurabh Sharma saura.nosp@m.bh2@.nosp@m.andre.nosp@m.w.cm.nosp@m.u.edu
Function Documentation
void i2c_master_init (uint16_t clk)
initializes the I2C module
Parameters
clk bus clock speed
References CLEAR_FIFO, CLEAR_FLAGS, gpio_config(), GPIO_FUN_ALT0, GPIO_PULL_UP, gpio_set_pull(), I2C1_SCL, I2C1_SDA, I2C_CLK_100KHZ, i2c_clkdivider_reg, i2c_control_reg, I2C_ENB, and i2c_status_reg.
Referenced by adc_init().
uint8_t i2c_master_read (uint8_t * buf, uint16_t len, uint8_t addr)
reads from I2C device
Parameters
buf pointer to input data buffer
len number of bytes to read
addr slave device address
References CLEAR_FIFO, CLEAR_FLAGS, DONE_XFER, ENB_READ, ENB_TRANSFER, i2c_address_reg, i2c_control_reg, i2c_dlen_reg, i2c_fifo_reg, and i2c_status_reg.
Referenced by adc_read().
uint8_t i2c_master_write (uint8_t * buf, uint16_t len, uint8_t addr)
writes to I2C device
Parameters
buf pointer to output data buffer
len length of output data buffer in bytes
addr slave device address
References CLEAR_FIFO, CLEAR_FLAGS, DONE_XFER, ENB_TRANSFER, ENB_WRITE, i2c_address_reg, i2c_control_reg, i2c_dlen_reg, i2c_fifo_reg, i2c_status_reg, and TXD.
Referenced by adc_read().