18-349 Kernel: kernel.c File Reference
kernel.c File Reference
entry point to the raspberry pi kernel
#include <printk.h>
#include <uart.h>
#include <kstdint.h>
#include <ads1015.h>
#include <i2c.h>
#include <arm.h>
#include <timer.h>
#include <supervisor.h>
#include <syscalls.h>
#include <screen.h>
Macros
#define INT16_MAX 0xFFFF
Max uint16_t.
#define LIGHT_CHANNEL 3
Light channel number.
#define SOUND_CHANNEL 2
Sound channel number.
#define CLAP_THRESHOLD 20000
Threshold value for clap sound.
#define SAMPLES 200
Number of samples to take for audio.
#define SOUND_SENSOR 49
ASCII VALUE for 1.
#define LIGHT_SENSOR 48
ASCII VALUE FOR 0.
#define TCB_ENTRIES 18
Entries in TCB that need to be stored.
#define IDLE_PRIO 31
Priority of idle thread.
#define COLUMNS 126
Columns on oled screen.
Functions
void kernel_main (void)
The kernel entry point.
void scheduler (void *data)
Scheduler.
void update_screen ()
handle the updating of screen every time interval this will be called every interval make the screen black by using oled_buf_draw and append columns to the current buffer if not multiple of 128 time intervals
void * irq_c_handler (void *data)
Handler called when an IRQ occurs.
void * swi_c_handler (int swi_num, int *args)
Handles the given swi_num.
Variables
volatile int wait_check
Keep track of wait for wait until next period.
volatile uint32_t timer_count
Global timer that counts up every interrupt (1milli)
volatile uint32_t runnable_pool
Runnable pool.
volatile uint32_t waiting_pool
Waiting pool.
volatile struct mutex * mutex_pool [32]
Mutex pool count for each priority.
static int column_count = 0
Current column on oled screen.
void(* sample_fn)(uint16_t)
Define this in kernel.c.
Detailed Description
entry point to the raspberry pi kernel
Date
9/24/2016
Author
Philip Lee plee2.nosp@m.@and.nosp@m.rew.c.nosp@m.mu.e.nosp@m.du
Saurabh Sharma saura.nosp@m.bh2@.nosp@m.andre.nosp@m.w.cm.nosp@m.u.edu
Tong Bian tbian.nosp@m.@and.nosp@m.rew.c.nosp@m.mu.e.nosp@m.du
Function Documentation
void scheduler (void * data)
Scheduler.
Find next runnable task in pool.
Returns
Pointer to new context to resume
References TCBBlock::C, TCBBlock::computed, curr_tcb, IDLE_PRIO, TCBBlock::next_period, mutex::owner, mutex::priority, TCBBlock::priority_old, runnable_pool, TCBBlock::status, TCBBlock::T, tcb, TCB_ENTRIES, timer_count, waiting_pool, and TCBBlock::wake.
Referenced by irq_c_handler().
void* swi_c_handler (int swi_num, int * args)
Handles the given swi_num.
Parameters
swi_num the swi number passed in from swi_asm_handler
args pointer to arguments array, set up by the swi_asm_handler
Returns
the return result of the syscall
References get_time(), mutex_init(), mutex_lock(), mutex_unlock(), NULL, scheduler_start(), syscall_close(), syscall_exit(), syscall_fstat(), syscall_isatty(), syscall_lseek(), syscall_read(), syscall_sample_adc_start(), syscall_sample_adc_stop(), syscall_sbrk(), syscall_write(), thread_create(), thread_init(), and wait_until_next_period().