18-349 Kernel: syscalls.c File Reference
syscalls.c File Reference
Implementation of syscalls needed for newlib and 349 custom syscalls.
#include <kstdint.h>
#include <printk.h>
#include <timer.h>
#include <arm.h>
#include <psr.h>
#include <syscalls.h>
Macros
#define EOT 4
End of Transmission ASCII value.
#define BACKSPACE 8
Backspace ASCII value.
#define DELETE 127
Delete ASCII value.
#define NEWLINE 10
Newline ASCII value.
#define RETURN 13
Return ASCII value.
#define STDOUT 1
STDOUT value.
#define STDIN 0
STDIN value.
#define IDLE_PRIO 31
IDLE val.
#define TICKS 500
Ticks per second for timer.
#define NO_OWNER 99
If mutex has no owner, priority == 99.
Functions
uint8_t uart_get_byte (void)
reads a byte over UART
void uart_put_byte (uint8_t)
sends a byte over UART
int thread_init (thread_fn idle_fn, uint32_t *idle_stack_start)
Initialize the thread library.
int thread_create (thread_fn fn, uint32_t *stack_start, unsigned int prio, unsigned int C, unsigned int T)
Create a new thread running the given function.
int scheduler_start (void)
Allow the kernel to start running the added task set.
void wait_until_next_period (void)
Efficiently waits to run until the next period.
int mutex_init (mutex_t *mutex, unsigned int max_prio)
Initialize the mutex.
void mutex_lock (mutex_t *mutex)
Lock the mutex.
void mutex_unlock (mutex_t *mutex)
Unlock the mutex.
unsigned int get_time (void)
Get the current time in milliseconds.
void syscall_exit (int status)
Print out the exit status of the user program and hang with interrupts disabled (this is different behavior than the Linux man pages!)
int syscall_write (int file, char *ptr, int len)
See linux man page for write.
int syscall_read (int file, char *ptr, int len)
See linux man page for read.
int syscall_sample_adc_start (int freq, uint8_t channel, void(*callback)(uint16_t))
Starts sampling the ADC periodically, calling the given callback with the ADC sample value.
int syscall_sample_adc_stop ()
Stops periodic sampling of the ADC.
void * syscall_sbrk (int incr)
See linux man page for sbrk.
int syscall_close (int file)
See linux man page for close. Since we only read/write to stdin/stdout, close doesn't really do anything.
int syscall_fstat (int file, void *st)
See linux man page for fstat. Since we don't have a file system, this doesn't actually do anything.
int syscall_isatty (int file)
See linux man page for isatty. Our implementation always returns TRUE since we only use stdin and stdout.
int syscall_lseek (int file, int ptr, int dir)
See linux man page for lseek. Not implemented in our kernel since we don't have a filesystem.
Variables
static volatile int thread_num
number of created threads
static volatile uint32_t created
created status array
volatile uint32_t runnable_pool = 0
Runnable pool.
volatile uint32_t waiting_pool = 0
Waiting pool.
volatile struct TCBBlock tcb [32] = {{0}}
TCB.
volatile struct TCBBlock * curr_tcb
global variable to point to tcb of current thread
static volatile float sum_U
total Utility of all the created threads
volatile int wait_check
Keep track of wait for wait until next period.
volatile uint32_t timer_count
Global timer that counts up every interrupt (1milli)
volatile struct mutex * mutex_pool [32] = {0}
Mutex pool count for each priority.
char * heap_end = 0
Global variable to keep track of where our heap ends.
volatile int adc_channel = 2
Global variable for adc channel.
static float U_val [32]
Values for U for up to 32 threads.
void(* sample_fn)(uint16_t)
Define this in kernel.c.
Detailed Description
Implementation of syscalls needed for newlib and 349 custom syscalls.
Date
10/14/2016
Author
Philip Lee plee2.nosp@m.@and.nosp@m.rew.c.nosp@m.mu.e.nosp@m.du
Saurabh Sharma saura.nosp@m.bh2@.nosp@m.andre.nosp@m.w.cm.nosp@m.u.edu
Tong Bian tbian.nosp@m.@and.nosp@m.rew.c.nosp@m.mu.e.nosp@m.du
Function Documentation
int mutex_init (mutex_t * mutex, unsigned int max_prio)
Initialize the mutex.
A user program must call this initializer before attempting to lock or unlock the mutex. You can assume that this initializer will only be called once by any test programs.
Parameters
mutex The mutex to act on.
max_prio The maximum priority of a thread which could use
Returns
0 on success or -1 on failure
References NO_OWNER, mutex::owner, and mutex::priority.
Referenced by swi_c_handler().
void mutex_lock (mutex_t * mutex)
Lock the mutex.
This function will not return (may block) until the current thread has exclusive rights to the mutex. You can assume the mutex has been initialized.
Parameters
mutex The mutex to act on.
References disable_interrupts(), enable_interrupts(), IDLE_PRIO, NO_OWNER, mutex::owner, mutex::priority, TCBBlock::priority, and TCBBlock::priority_old.
Referenced by swi_c_handler().
void mutex_unlock (mutex_t * mutex)
Unlock the mutex.
Parameters
mutex The mutex to act on.
References IDLE_PRIO, NO_OWNER, mutex::owner, TCBBlock::priority, and TCBBlock::priority_old.
Referenced by swi_c_handler().
int scheduler_start (void)
Allow the kernel to start running the added task set.
This function should enable IRQs and thus enable your scheduler. The kernel will test that a task set with this new task is scheduleable before running and may return an error if this is not the case.
Returns
0 on success or -1 on failure
References enable_interrupts(), TICKS, and timer_start().
Referenced by swi_c_handler().
int syscall_close (int file)
See linux man page for close. Since we only read/write to stdin/stdout, close doesn't really do anything.
Parameters
file file descriptor to close.
Returns
-1 on error, 0 on success.
Referenced by swi_c_handler().
void syscall_exit (int status)
Print out the exit status of the user program and hang with interrupts disabled (this is different behavior than the Linux man pages!)
Parameters
status Exit status to return to the kernel
References disable_interrupts(), and printk().
Referenced by swi_c_handler().
int syscall_fstat (int file, void * st)
See linux man page for fstat. Since we don't have a file system, this doesn't actually do anything.
Parameters
file file descriptor to examine
st pointer to stat structure
Returns
-1 on error, 0 on success
Referenced by swi_c_handler().
int syscall_isatty (int file)
See linux man page for isatty. Our implementation always returns TRUE since we only use stdin and stdout.
Parameters
file file descriptor to check.
Returns
boolean (1 or 0) indicating whether the fd is a tty
Referenced by swi_c_handler().
int syscall_lseek (int file, int offset, int whence)
See linux man page for lseek. Not implemented in our kernel since we don't have a filesystem.
Parameters
file file descriptor
offset offset
whence see man page for appropriate values
Returns
-1 on error, 0 on success
Referenced by swi_c_handler().
int syscall_read (int file, char * ptr, int len)
See linux man page for read.
Reads until all len bytes are read or newline/return is found. Detects backspace and EOL characters and handles them appropriately.
The idea is to mimic normal terminal reading input, that is, if the user hits backspace it should erase the previously read character.
Parameters
file file descriptor to read from. We only support STDIN.
ptr pointer to buffer to read from
len max length to rea dread *
Returns
-1 on error, otherwise number of bytes read
References BACKSPACE, DELETE, EOT, NEWLINE, printk(), RETURN, STDIN, and uart_get_byte().
Referenced by swi_c_handler().
int syscall_sample_adc_start (int freq, uint8_t channel, void(*)(uint16_t) callback)
Starts sampling the ADC periodically, calling the given callback with the ADC sample value.
Parameters
freq frequency at which to sample
channel channel to sample
callback function to be called everytime a sample is read from adc.
Returns
0 on success or -1 on failure
References adc_channel, sample_fn, and timer_start().
Referenced by swi_c_handler().
int syscall_sample_adc_stop ()
Stops periodic sampling of the ADC.
Returns
0 on success or -1 on failure
References timer_stop().
Referenced by swi_c_handler().
void* syscall_sbrk (int incr)
See linux man page for sbrk.
Parameters
incr amount to increment data segment size by.
Returns
-1 if error, or the previous end address of the heap
References heap_end.
Referenced by swi_c_handler().
int syscall_write (int file, char * ptr, int len)
See linux man page for write.
Parameters
file file descriptor to write to. We only support STDOUT.
ptr pointer to buffer to write to
len max length to write
Returns
-1 on error, otherwise the number of bytes written
References STDOUT, and uart_put_byte().
Referenced by swi_c_handler().
int thread_create (thread_fn fn, uint32_t * stack_start, unsigned int prio, unsigned int C, unsigned int T)
Create a new thread running the given function.
Parameters
fn Pointer to the function to run in the new thread.
stack_start Pointer to the first valid location of this thread's stack.
prio Priority of this thread. Lower number are higher priority.
C Real time execution time (ms).
T Real time task period (ms).
Returns
0 on success or -1 on failure
out of utility bound
References TCBBlock::C, TCBBlock::computed, created, IDLE_PRIO, TCBBlock::lr_irq, TCBBlock::next_period, printk(), TCBBlock::priority, TCBBlock::priority_old, PSR_MODE_USR, runnable_pool, TCBBlock::sp, TCBBlock::spsr_irq, TCBBlock::status, sum_U, TCBBlock::T, thread_num, U_val, and TCBBlock::wake.
Referenced by swi_c_handler().
int thread_init (thread_fn idle_fn, uint32_t * idle_stack_start)
Initialize the thread library.
A user program must call this initializer before attempting to create any threads or start the scheduler.
Parameters
idle_fn Pointer to a thread function to run when no other threads are runnable.
idle_stack_start Pointer to the first valid location of idle thread's stack.
Returns
0 on success or -1 on failure
References TCBBlock::C, created, IDLE_PRIO, TCBBlock::lr_irq, TCBBlock::priority, PSR_MODE_USR, runnable_pool, TCBBlock::sp, TCBBlock::spsr_irq, TCBBlock::spsr_svc, TCBBlock::status, sum_U, TCBBlock::T, thread_num, timer_count, wait_check, and waiting_pool.
Referenced by swi_c_handler().
uint8_t uart_get_byte (void)
reads a byte over UART
Returns
the byte received
References aux_mu_ier_reg, aux_mu_io_reg, aux_mu_lsr_reg, CLEAR_SEND, and RECEIVE_DONE.
Referenced by syscall_read().
void uart_put_byte (uint8_t byte)
sends a byte over UART
Parameters
byte the byte to send
References aux_mu_io_reg, aux_mu_lsr_reg, aux_mu_stat_reg, SEND_DONE, and STAT_READY.
Referenced by syscall_write().
Variable Documentation
float U_val[32] static
Initial value:
= {1.0, 0.828, 0.779, 0.756, 0.743, 0.734, 0.729, 0.724,
  0.721, 0.718, 0.715, 0.714, 0.712, 0.711, 0.709, 0.708, 0.707, 0.707, 0.706,
  0.705, 0.705, 0.704, 0.704, 0.703, 0.703, 0.702, 0.702, 0.702, 0.701, 0.701,
  0.701, 0.701}
Values for U for up to 32 threads.
Referenced by thread_create().