18-349 Kernel: timer.h File Reference
timer.h File Reference
Routines for interacting with the ARM timer.
#include <kstdint.h>
Functions
void timer_start (int freq)
Configures the arm timer to start running with the given frequency. The Timer should run in 32 bit mode, with a prescaler of 1, and with interrupts enabled.
void timer_stop (void)
Disables timer IRQs.
int timer_is_pending (void)
Determines if there is currently a pending timer interrupt.
void timer_clear_pending (void)
Should be called to acknowledge that a timer interrupt occurred and has been appropriately handled. Will clear the pending bit in the timer's MMIO registers.
Detailed Description
Routines for interacting with the ARM timer.
Date
September 26, 2015
Author
Kenneth Li kyli@.nosp@m.andr.nosp@m.ew.cm.nosp@m.u.ed.nosp@m.u
Function Documentation
int timer_is_pending (void)
Determines if there is currently a pending timer interrupt.
Returns
1 if timer interrupt is pending, 0 if not.
References basic_pending, and PENDING.
Referenced by irq_c_handler().
void timer_start (int freq)
Configures the arm timer to start running with the given frequency. The Timer should run in 32 bit mode, with a prescaler of 1, and with interrupts enabled.
Parameters
freq frequency at which to run the timer
References basic_enable, CLEAR, FREQ_1MHZ, timer_control, timer_irq_clear, timer_load, TIMER_MAX, timer_predivider, timer_reload, TIMER_START, and TOGGLE.
Referenced by scheduler_start(), and syscall_sample_adc_start().