18-349 Kernel: timer.c File Reference
timer.c File Reference
Implementation of routines for interacting with ARM timer.
#include <timer.h>
#include <kstdint.h>
#include <printk.h>
#include <BCM2836.h>
Macros
#define IRQ_BASIC_PENDING_REG (volatile uint32_t*)(MMIO_BASE_PHYSICAL+0xB200)
physical address of IRQ basic pending register
#define IRQ_BASIC_ENABLE_REG (volatile uint32_t*)(MMIO_BASE_PHYSICAL+0xB218)
physical address of IRQ basic pending register
#define IRQ_BASIC_DISABLE_REG (volatile uint32_t*)(MMIO_BASE_PHYSICAL+0xB224)
physical address of IRQ basic pending register
#define TIMER_LOAD_REG (volatile uint32_t *)(MMIO_BASE_PHYSICAL+0x00B400)
physical address of timer load register
#define TIMER_VALUE_REG (volatile uint32_t *)(MMIO_BASE_PHYSICAL+0x00B404)
physical address of timer value register
#define TIMER_CONTROL_REG (volatile uint32_t *)(MMIO_BASE_PHYSICAL+0x00B408)
physical address of timer control register
#define TIMER_IRQ_CLEAR (volatile uint32_t *)(MMIO_BASE_PHYSICAL+0x00B40C)
physical address of timer IRQ clear register
#define TIMER_IRQ_MASKED_REG (volatile uint32_t *)(MMIO_BASE_PHYSICAL+0x00B414)
physical address of timer IRQ masked register
#define TIMER_RELOAD_REG (volatile uint32_t *)(MMIO_BASE_PHYSICAL +0x00B418)
physical address of timer reload register
#define TIMER_PREDIVIDER_REG (volatile uint32_t *)(MMIO_BASE_PHYSICAL +0x00B41C)
physical address of timer predivider
#define TOGGLE 1
Toggle basic ARM Timer interrupts.
#define PENDING 1
ARM Timer pending interrupt.
#define CLEAR 1
ARM Timer clear interrupt.
#define TIMER_MAX 1000000
ARM Timer 1sec value for 100Mhz.
#define FREQ_1MHZ 249
ARM timer predivider for 1Mhz.
#define TIMER_STOP 0x10322
ARM control stop timer.
#define TIMER_START 0xA2
ARM control start timer.
Functions
void timer_stop (void)
Disables timer IRQs.
int timer_is_pending (void)
Determines if there is currently a pending timer interrupt.
void timer_clear_pending (void)
Should be called to acknowledge that a timer interrupt occurred and has been appropriately handled. Will clear the pending bit in the timer's MMIO registers.
void timer_start (int freq)
Configures the arm timer to start running with the given frequency. The Timer should run in 32 bit mode, with a prescaler of 1, and with interrupts enabled.
Variables
static volatile uint32_t * basic_pending = (volatile uint32_t*) IRQ_BASIC_PENDING_REG
irq basic pending
static volatile uint32_t * basic_enable = (volatile uint32_t*) IRQ_BASIC_ENABLE_REG
irq basic pending
static volatile uint32_t * basic_disable = (volatile uint32_t*) IRQ_BASIC_DISABLE_REG
irq basic pending
static volatile uint32_t * timer_load = (volatile uint32_t*) TIMER_LOAD_REG
timer load register set
static volatile uint32_t * timer_control = (volatile uint32_t*) TIMER_CONTROL_REG
timer value register set
static volatile uint32_t * timer_irq_clear = (volatile uint32_t*) TIMER_IRQ_CLEAR
timer control register set
static volatile uint32_t * timer_reload = (volatile uint32_t*) TIMER_RELOAD_REG
timer control register set
static volatile uint32_t * timer_predivider = (volatile uint32_t*) TIMER_PREDIVIDER_REG
timer predivider register set
Detailed Description
Implementation of routines for interacting with ARM timer.
Date
10/5/2016
Author
Philip Lee plee2.nosp@m.@and.nosp@m.rew.c.nosp@m.mu.e.nosp@m.du
Function Documentation
int timer_is_pending (void)
Determines if there is currently a pending timer interrupt.
Returns
1 if timer interrupt is pending, 0 if not.
References basic_pending, and PENDING.
Referenced by irq_c_handler().
void timer_start (int freq)
Configures the arm timer to start running with the given frequency. The Timer should run in 32 bit mode, with a prescaler of 1, and with interrupts enabled.
Parameters
freq frequency at which to run the timer
References basic_enable, CLEAR, FREQ_1MHZ, timer_control, timer_irq_clear, timer_load, TIMER_MAX, timer_predivider, timer_reload, TIMER_START, and TOGGLE.
Referenced by scheduler_start(), and syscall_sample_adc_start().
Variable Documentation
volatile uint32_t* timer_control = (volatile uint32_t*) TIMER_CONTROL_REG static
timer value register set
timer control register set
Referenced by timer_start().
volatile uint32_t* timer_reload = (volatile uint32_t*) TIMER_RELOAD_REG static
timer control register set
timer reload register set
Referenced by timer_start().