18-349 Kernel: uart.c File Reference
uart.c File Reference
lower level hardware interactions for uart on pi
#include <BCM2836.h>
#include <kstdint.h>
#include <gpio.h>
Macros
#define RX_PIN 15
GPIO UART RX pin.
#define TX_PIN 14
GPIO UART TX pin.
#define BAUD_RATE 270
Sets baud rate to desired 115200.
#define IER_DISABLE_INTERRUPTS 0
Disable interrupts in IER.
#define IIR_SET 198
Set IIR to 198 to enable and clear fifo.
#define ENABLE_UART 3
Enable UART in control reg.
#define ENABLE 1
Enable UART.
#define DISABLE 0
Disable UART.
#define IIR_CLEAR 0x6;
Clear FIFO.
#define CLEAR_SEND 0x2
Clear send FIFO.
#define SEND_DONE 0x20
Send FIFO done.
#define STAT_READY 0x200
STat ready check.
#define RECEIVE_DONE 0x1
Receive FIFO done.
#define AUX_MU_BAUD_REG (volatile uint32_t *)(MMIO_BASE_PHYSICAL + 0x215068)
physical address of AUX_MU_BAUD register
#define AUXENB_REG (volatile uint32_t *)(MMIO_BASE_PHYSICAL + 0x215004)
physical address of AUXENB register for MMIO
#define AUX_MU_IO_REG_REG (volatile uint32_t *)(MMIO_BASE_PHYSICAL + 0x215040)
physical address of AUX_MU_IO_REG register
#define AUX_MU_IER_REG_REG (volatile uint32_t *)(MMIO_BASE_PHYSICAL + 0x215044)
physical address of AUX_MU_IER_REG register
#define AUX_MU_IIR_REG_REG (volatile uint32_t *)(MMIO_BASE_PHYSICAL + 0x215048)
physical address of AUX_MU_IIR_REG register
#define AUX_MU_LCR_REG_REG (volatile uint32_t *)(MMIO_BASE_PHYSICAL + 0x21504C)
physical address of AUX_MU_LCR_REG register
#define AUX_MU_LSR_REG_REG (volatile uint32_t *)(MMIO_BASE_PHYSICAL + 0x215054)
physical address of AUX_MU_LSR_REG register
#define AUX_MU_CNTL_REG_REG (volatile uint32_t *)(MMIO_BASE_PHYSICAL + 0x215060)
physical address of AUX_MU_CNTL_REG register
#define AUX_MU_STAT_REG_REG (volatile uint32_t *)(MMIO_BASE_PHYSICAL + 0x215064)
physical address of AUX_MU_STAT_REG
Functions
void uart_init (void)
initializes UART to 115200 baud in 8-bit mode
void uart_close (void)
closes UART
void uart_put_byte (uint8_t byte)
sends a byte over UART
uint8_t uart_get_byte (void)
reads a byte over UART
Variables
static volatile uint32_t * aux_mu_baud = (volatile uint32_t*) AUX_MU_BAUD_REG
aux_mu_baud register set
static volatile uint32_t * auxenb = (volatile uint32_t*) AUXENB_REG
auxenb register set
static volatile uint32_t * aux_mu_ier_reg = (volatile uint32_t*) AUX_MU_IER_REG_REG
aux_mu_ier_reg register set
static volatile uint32_t * aux_mu_iir_reg = (volatile uint32_t*) AUX_MU_IIR_REG_REG
aux_mu_iier_reg register set
static volatile uint32_t * aux_mu_lcr_reg = (volatile uint32_t*) AUX_MU_LCR_REG_REG
aux_mu_lcr register set
static volatile uint32_t * aux_mu_io_reg = (volatile uint32_t*) AUX_MU_IO_REG_REG
aux_mu_io_reg register set
static volatile uint32_t * aux_mu_cntl_reg = (volatile uint32_t*) AUX_MU_CNTL_REG_REG
AUX_MU_CNTL_REG register set.
static volatile uint32_t * aux_mu_lsr_reg = (volatile uint32_t*) AUX_MU_LSR_REG_REG
AUX_MU_LSR_REG register set.
static volatile uint32_t * aux_mu_stat_reg = (volatile uint32_t*) AUX_MU_STAT_REG_REG
AUX_MU_STAT_REG register set.
Detailed Description
lower level hardware interactions for uart on pi
Date
9/24/2016
Author
Philip Lee plee2.nosp@m.@and.nosp@m.rew.c.nosp@m.mu.e.nosp@m.du
Saurabh Sharma saura.nosp@m.bh2@.nosp@m.andre.nosp@m.w.cm.nosp@m.u.edu
Tong Bian tbian.nosp@m.@and.nosp@m.rew.c.nosp@m.mu.e.nosp@m.du
Function Documentation
uint8_t uart_get_byte (void)
reads a byte over UART
Returns
the byte received
References aux_mu_ier_reg, aux_mu_io_reg, aux_mu_lsr_reg, CLEAR_SEND, and RECEIVE_DONE.
Referenced by syscall_read().
void uart_put_byte (uint8_t byte)
sends a byte over UART
Parameters
byte the byte to send
References aux_mu_io_reg, aux_mu_lsr_reg, aux_mu_stat_reg, SEND_DONE, and STAT_READY.
Referenced by printk(), printnumk(), and syscall_write().